# Generated by Django 2.0.1 on 2019-01-08 06:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfluenceWikiPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('space', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DbScripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('script', models.TextField(blank=True, null=True)),
                ('execution_sequence', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('issue_title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sprint_start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('sprint_end_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JiraUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('jira_user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('jira_password', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('can_create_upd', models.BooleanField(default=True)),
                ('can_create_ppd', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('project_key', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_owner', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PushDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('key', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.IntegerField(choices=[(2, 'UPD'), (2, 'PPD')], default=1)),
                ('version', models.IntegerField()),
                ('version_description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sprint_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sprint_start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('sprint_end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_ticket.Project')),
                ('push_deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_ticket.PushDeployment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='assiginee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_ticket.JiraUser'),
        ),
        migrations.AddField(
            model_name='issue',
            name='push_deployment_db_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_tickets', to='deploy_ticket.PushDeployment'),
        ),
        migrations.AddField(
            model_name='issue',
            name='push_deployment_main_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infra_ticket', to='deploy_ticket.PushDeployment'),
        ),
        migrations.AddField(
            model_name='issue',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_ticket.Sprint'),
        ),
        migrations.AddField(
            model_name='dbscripts',
            name='assiginee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_ticket.JiraUser'),
        ),
        migrations.AddField(
            model_name='dbscripts',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_ticket.Issue'),
        ),
        migrations.AddField(
            model_name='dbscripts',
            name='push_deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_ticket.PushDeployment'),
        ),
        migrations.AddField(
            model_name='confluencewikipage',
            name='push_deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_ticket.PushDeployment'),
        ),
    ]
