# Generated by Django 2.0.1 on 2019-01-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdeployment',
            name='status',
            field=models.IntegerField(choices=[(2, 'UPD'), (2, 'PPD')], default=1),
        ),
        migrations.AlterField(
            model_name='pushdeployment',
            name='version',
            field=models.IntegerField(choices=[(1, 'Started Push deployment ticket Creation Process'), (2, 'Fetching issues from current Sprint'), (3, 'Fetching latest migration scripts from db confluence doc'), (4, 'Creating INFRA database tickets for migration queries'), (5, 'Creating a new confluence doc with steps for this push deployment'), (6, 'Creating final infra ticket for this push deployment'), (7, 'Push deployment ticket creation process completed')], default=1),
        ),
    ]
