# Generated by Django 2.0.1 on 2019-01-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_ticket', '0002_auto_20190109_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdeployment',
            name='releasing_sprint_display_name',
            field=models.CharField(default='Sprint 14th Aug', help_text='Will be displayed on PD Confluence page Ex. Sprint 14th Aug', max_length=250),
        ),
        migrations.AddField(
            model_name='pushdeployment',
            name='scheduled_maintainance_window',
            field=models.CharField(default='Aug 16th, 2018 (PST)', help_text='Will be displayed on PD Confluence page Ex. Aug 16th, 2018 (PST)', max_length=250),
        ),
        migrations.AddField(
            model_name='pushdeployment',
            name='scheduled_release_date',
            field=models.CharField(default='08/16/2018 LA, US ;  08/17/2018 New Delhi', help_text='Will be displayed on PD Confluence page Ex. 08/16/2018 LA, US ;  08/17/2018 New Delhi', max_length=250),
        ),
        migrations.AddField(
            model_name='pushdeployment',
            name='scheduled_release_time',
            field=models.CharField(default='8:00 PM PST', help_text='Will be displayed on PD Confluence page Ex. 8:00 PM PST', max_length=250),
        ),
        migrations.AlterField(
            model_name='pushdeployment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Started Push deployment ticket Creation Process'), (2, 'Fetching issues from current Sprint'), (3, 'Fetching latest migration scripts from db confluence doc'), (4, 'Creating INFRA database tickets for migration queries'), (5, 'Creating a new confluence doc with steps for this push deployment'), (6, 'Creating final infra ticket for this push deployment'), (7, 'Push deployment ticket creation process completed')], default=1),
        ),
        migrations.AlterField(
            model_name='pushdeployment',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
