# Generated by Django 2.0.1 on 2019-01-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_ticket', '0004_auto_20190110_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jirauser',
            name='can_create_upd',
            field=models.BooleanField(default=False),
        ),
    ]
