# Generated by Django 2.0.1 on 2019-01-14 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_ticket', '0005_auto_20190114_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='push_deployment_db_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_tickets', to='deploy_ticket.PushDeployment'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='push_deployment_main_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infra_ticket', to='deploy_ticket.PushDeployment'),
        ),
    ]
