# Generated by Django 2.0.1 on 2019-01-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_ticket', '0006_auto_20190114_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbscripts',
            old_name='assiginee',
            new_name='assignee',
        ),
        migrations.AddField(
            model_name='dbscripts',
            name='sprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deploy_ticket.Sprint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pushdeployment',
            name='type',
            field=models.IntegerField(choices=[(1, 'UPD'), (2, 'PPD')], default=1),
        ),
    ]
