# Generated by Django 2.0.1 on 2019-01-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_ticket', '0007_auto_20190114_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbscripts',
            name='assignee',
        ),
    ]
