# Generated by Django 2.0.1 on 2019-01-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_ticket', '0008_remove_dbscripts_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdeployment',
            name='artifact_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushdeployment',
            name='installation_file_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
