# Generated by Django 2.0.1 on 2019-01-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_ticket', '0009_auto_20190114_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='confluencewikipage',
            name='page_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
