# Generated by Django 2.0.1 on 2019-01-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_ticket', '0011_confluencewikipage_ui_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdeployment',
            name='build_no',
            field=models.CharField(default='....To be filled....', help_text='Finalised build no which will be on UPD/PPD infra ticket', max_length=250),
        ),
    ]
